const jCatagory = [
  {
    index: 0,
    image: "../images/google.png",
    title: "web Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Google",
    location: "USA",
    vacancy: "01",
    hours: "50h/week",
    description:
      "Join Google as a software engineer to build scalable, innovative solutions. Proficiency in Java, Python, and cloud technologies is required. Collaborate with cross-functional teams to solve complex challenges. Freshers are welcome",
    workplace: "Work from home",
    education: "bachelor degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
  {
    index: 1,
    image: "../images/uber.png",
    title: "Sql Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Uber",
    location: "USA",
    vacancy: "02",
    hours: "50h/week",
    description:
      "Join uber as a software engineer to build scalable, innovative solutions. Proficiency in Java, Python, and cloud technologies is required. Collaborate with cross-functional teams to solve complex challenges. Freshers are welcome",
    workplace: "Work from office",
    education: "bachelor degree in any Computer Science Course.",
    experience: "2 to 5 year(s)",
  },
  {
    index: 2,
    image: "../images/linkedin.png",
    title: "Java Developer",
    rate: "$900-1200/m",
    av: "Part Time",
    companyName: "Linkdin",
    location: "Canada",
    vacancy: "03",
    hours: "45h/week",
    description:
      "Linkdin is hiring Java Developer skilled in core java, Spring Boot, and cloud computing. The role involves building scalable microservices and maintaining APIs.",
    workplace: "On-site",
    education: "Bachelor's or Master's degree in Computer Science.",
    experience: "4 to 7 year(s)",
  },
  {
    index: 3,
    image: "../images/facebook.png",
    title: "SQL Developer",
    rate: "$900-1200/m",
    av: "Full Time",
    companyName: "Facebook",
    location: "Germany",
    vacancy: "01",
    hours: "40h/week",
    description:
      "Facebook is looking for a SQL Developer to manage and optimize databases, ensuring data integrity and availability. Familiarity with SQL, database design, and reporting tools is required.",
    workplace: "Remote",
    education: "Bachelor's degree in any field.",
    experience: "1 to 3 year(s)",
  },
  {
    index: 4,
    image: "../images/yahoo.png",
    title: "Digital Marketing",
    rate: "$900-1200/m",
    av: "Part Time",
    companyName: "Yahoo",
    location: "India",
    vacancy: "04",
    hours: "20h/week",
    description:
      "Yahoo is seeking a Digital Marketing Specialist to manage campaigns across various channels, including social media, email, and search engines. Familiarity with analytics tools and SEO practices is essential.",
    workplace: "Work from home",
    education: "Bachelor's degree in Marketing or related field.",
    experience: "1 to 3 year(s)"
  }
];